# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build web

on:
  push:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16]
        
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@main
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
            cd simple-mind-map
            npm i
            npm link
            cd ..
            cd web
            npm i
            npm link simple-mind-map
            npm run build

        # find $PWD -maxdepth 1 | xargs ls -ld
        # cd ..
        # find $PWD -maxdepth 1 | xargs ls -ld


    - name: Upload a Build Artifact
      uses: actions/upload-artifact@main
      with:
        name: mind-map-${{ matrix.node-version }}
        path: web/dist
